### ISSUE TITLE
Need help healing eyes

### ISSUE THREAD

**Issue by christopherpeart** [KeyboardFire/hotdog.vim#2]
I kan't sea from tears of pain or july. Kan't tell what one it is. Using voice recognition to wrate thas so speeling may be bid. Please send help. 🌭🌭/10

**Comment by TehFlaminTaco** [comment]
Not a bug.

**Comment by christopherpeart** [comment]
Its a featare

**Comment by christopherpeart** [comment]
Update: Eyes have staped having tears and I think et is ketchup flowing from me i's

**Comment by tckmn** [comment]
everything is working as intended here; I don't see the problem with this
